version: "3.1"
services:
  api-gateway-service:
    build: ./api-gateway
    ports: 
      - 9000:9000
    env_file:
      - docker-compose.env
  redis-service:
    image: redis:rc-alpine3.12
    ports: 
      - 6379:6379
  front-end-service:
    build: ./front-end
    ports: 
      - 3000:3000
  orders-service:
    build: ./orders-service
    env_file:
      - docker-compose.env
  shipment-service:
    build: ./shipment-service
    env_file:
      - docker-compose.env
  routing-solver-service:
    build: ./routing-solver-service
    ports:
      - 8080:8080
  directions-service:
    build: ./directions-service/
    ports:
      - 8989:8989
    command: /data/toronto.xml
    volumes: 
      - ./directions-service/data/:/data
    logging: 
      driver: none